# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'windowinformacion.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_windowinformacion(object):
    def setupUi(self, windowinformacion):
        windowinformacion.setObjectName("windowinformacion")
        windowinformacion.resize(378, 240)
        windowinformacion.setModal(True)
        self.btnBoxAviso = QtWidgets.QDialogButtonBox(windowinformacion)
        self.btnBoxAviso.setGeometry(QtCore.QRect(140, 170, 81, 61))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(7)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnBoxAviso.sizePolicy().hasHeightForWidth())
        self.btnBoxAviso.setSizePolicy(sizePolicy)
        self.btnBoxAviso.setMinimumSize(QtCore.QSize(0, 0))
        self.btnBoxAviso.setSizeIncrement(QtCore.QSize(1, 0))
        self.btnBoxAviso.setBaseSize(QtCore.QSize(2, 0))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.btnBoxAviso.setFont(font)
        self.btnBoxAviso.setAutoFillBackground(False)
        self.btnBoxAviso.setStandardButtons(QtWidgets.QDialogButtonBox.Ok)
        self.btnBoxAviso.setObjectName("btnBoxAviso")
        self.lblAviso = QtWidgets.QLabel(windowinformacion)
        self.lblAviso.setGeometry(QtCore.QRect(90, 80, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lblAviso.setFont(font)
        self.lblAviso.setObjectName("lblAviso")
        self.lblImageAviso = QtWidgets.QLabel(windowinformacion)
        self.lblImageAviso.setGeometry(QtCore.QRect(150, 20, 71, 71))
        self.lblImageAviso.setText("")
        self.lblImageAviso.setPixmap(QtGui.QPixmap("img/frutas.ico"))
        self.lblImageAviso.setScaledContents(True)
        self.lblImageAviso.setObjectName("lblImageAviso")
        self.lblAviso_2 = QtWidgets.QLabel(windowinformacion)
        self.lblAviso_2.setGeometry(QtCore.QRect(90, 110, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lblAviso_2.setFont(font)
        self.lblAviso_2.setObjectName("lblAviso_2")
        self.lblAviso_3 = QtWidgets.QLabel(windowinformacion)
        self.lblAviso_3.setGeometry(QtCore.QRect(90, 140, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lblAviso_3.setFont(font)
        self.lblAviso_3.setObjectName("lblAviso_3")

        self.retranslateUi(windowinformacion)
        QtCore.QMetaObject.connectSlotsByName(windowinformacion)

    def retranslateUi(self, windowinformacion):
        _translate = QtCore.QCoreApplication.translate
        windowinformacion.setWindowTitle(_translate("windowinformacion", "Acerca de Import/Export"))
        self.lblAviso.setText(_translate("windowinformacion", "Import-Export Copyright 2022"))
        self.lblAviso_2.setText(_translate("windowinformacion", "Author: Sol González Escolar"))
        self.lblAviso_3.setText(_translate("windowinformacion", "Versión: 0.0.1"))
import var
